
package co.com.kallsonys.esb.shipment;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-10-28T11:09:55.188-05:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "exceptionGeneric", targetNamespace = "http://www.kallsonys.com.co/cim/common/exceptiongeneric")
public class FulfillShipmentFault1 extends Exception {
    
    private co.com.kallsonys.esb.shipment.ExceptionGeneric exceptionGeneric;

    public FulfillShipmentFault1() {
        super();
    }
    
    public FulfillShipmentFault1(String message) {
        super(message);
    }
    
    public FulfillShipmentFault1(String message, Throwable cause) {
        super(message, cause);
    }

    public FulfillShipmentFault1(String message, co.com.kallsonys.esb.shipment.ExceptionGeneric exceptionGeneric) {
        super(message);
        this.exceptionGeneric = exceptionGeneric;
    }

    public FulfillShipmentFault1(String message, co.com.kallsonys.esb.shipment.ExceptionGeneric exceptionGeneric, Throwable cause) {
        super(message, cause);
        this.exceptionGeneric = exceptionGeneric;
    }

    public co.com.kallsonys.esb.shipment.ExceptionGeneric getFaultInfo() {
        return this.exceptionGeneric;
    }
}
