
package co.com.kallsonys.esb.shipment;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-10-28T11:09:55.095-05:00
 * Generated source version: 2.5.1
 * 
 */
public final class ShipmentCompanyPortType_ShipmentCompanyPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.kallsonys.com.co/cim/message/shipment/v1", "ShipmentCompanyService");

    private ShipmentCompanyPortType_ShipmentCompanyPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShipmentCompanyService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShipmentCompanyService ss = new ShipmentCompanyService(wsdlURL, SERVICE_NAME);
        ShipmentCompanyPortType port = ss.getShipmentCompanyPort();  
        
        {
        System.out.println("Invoking fulfillShipment...");
        co.com.kallsonys.esb.shipment.FulfillShipmentRq _fulfillShipment_fulfillShipmentRq = null;
        try {
            co.com.kallsonys.esb.shipment.FulfillShipmentRs _fulfillShipment__return = port.fulfillShipment(_fulfillShipment_fulfillShipmentRq);
            System.out.println("fulfillShipment.result=" + _fulfillShipment__return);

        } catch (FulfillShipmentFault1 e) { 
            System.out.println("Expected exception: FulfillShipment_fault1 has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkShipmentStatus...");
        co.com.kallsonys.esb.shipment.CheckShipmentStatusRq _checkShipmentStatus_checkShipmentStatusRq = null;
        try {
            co.com.kallsonys.esb.shipment.CheckShipmentStatusRs _checkShipmentStatus__return = port.checkShipmentStatus(_checkShipmentStatus_checkShipmentStatusRq);
            System.out.println("checkShipmentStatus.result=" + _checkShipmentStatus__return);

        } catch (CheckShipmentStatusFault1 e) { 
            System.out.println("Expected exception: CheckShipmentStatus_fault1 has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
