package co.com.kallsonys.esb.shipment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-10-28T11:09:55.202-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "ShipmentCompanyService", 
                  wsdlLocation = "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/03_Transport/wsdl/1.2/Transport.wsdl",
                  targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1") 
public class ShipmentCompanyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.kallsonys.com.co/cim/message/shipment/v1", "ShipmentCompanyService");
    public final static QName ShipmentCompanyPort = new QName("http://www.kallsonys.com.co/cim/message/shipment/v1", "ShipmentCompanyPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/03_Transport/wsdl/1.2/Transport.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ShipmentCompanyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/03_Transport/wsdl/1.2/Transport.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShipmentCompanyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShipmentCompanyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipmentCompanyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShipmentCompanyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShipmentCompanyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShipmentCompanyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ShipmentCompanyPortType
     */
    @WebEndpoint(name = "ShipmentCompanyPort")
    public ShipmentCompanyPortType getShipmentCompanyPort() {
        return super.getPort(ShipmentCompanyPort, ShipmentCompanyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShipmentCompanyPortType
     */
    @WebEndpoint(name = "ShipmentCompanyPort")
    public ShipmentCompanyPortType getShipmentCompanyPort(WebServiceFeature... features) {
        return super.getPort(ShipmentCompanyPort, ShipmentCompanyPortType.class, features);
    }

}
