package co.com.kallsonys.esb.shipment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-10-28T11:09:55.197-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1", name = "ShipmentCompanyPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ShipmentCompanyPortType {

    @WebMethod(action = "fulfillShipment")
    @WebResult(name = "FulfillShipmentRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1", partName = "FulfillShipmentRs")
    public FulfillShipmentRs fulfillShipment(
        @WebParam(partName = "FulfillShipmentRq", name = "FulfillShipmentRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1")
        FulfillShipmentRq fulfillShipmentRq
    ) throws FulfillShipmentFault1;

    @WebMethod(action = "checkShipmentStatus")
    @WebResult(name = "CheckShipmentStatusRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1", partName = "CheckShipmentStatusRs")
    public CheckShipmentStatusRs checkShipmentStatus(
        @WebParam(partName = "CheckShipmentStatusRq", name = "CheckShipmentStatusRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/shipment/v1")
        CheckShipmentStatusRq checkShipmentStatusRq
    ) throws CheckShipmentStatusFault1;
}
