package co.com.kallsonys.payment.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-01T18:20:43.278-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "CreditCardService", 
                  wsdlLocation = "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/kallsonysesb/src/main/resources/01_ESB/Message/02_Payment/wsdl/1.2/Payment.wsdl",
                  targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1") 
public class CreditCardService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.kallsonys.com.co/cim/message/payment/v1", "CreditCardService");
    public final static QName CreditCardPort = new QName("http://www.kallsonys.com.co/cim/message/payment/v1", "CreditCardPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/kallsonysesb/src/main/resources/01_ESB/Message/02_Payment/wsdl/1.2/Payment.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditCardService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/kallsonysesb/src/main/resources/01_ESB/Message/02_Payment/wsdl/1.2/Payment.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditCardService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditCardService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditCardService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CreditCardService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CreditCardPortType
     */
    @WebEndpoint(name = "CreditCardPort")
    public CreditCardPortType getCreditCardPort() {
        return super.getPort(CreditCardPort, CreditCardPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardPortType
     */
    @WebEndpoint(name = "CreditCardPort")
    public CreditCardPortType getCreditCardPort(WebServiceFeature... features) {
        return super.getPort(CreditCardPort, CreditCardPortType.class, features);
    }

}
