package co.com.kallsonys.payment.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-01T18:20:43.271-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1", name = "CreditCardPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreditCardPortType {

    @WebMethod(action = "verifyCreditCard")
    @WebResult(name = "VerifyCreditCardRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1", partName = "VerifyCreditCardRs")
    public VerifyCreditCardRs verifyCreditCard(
        @WebParam(partName = "VerifyCreditCardRq", name = "VerifyCreditCardRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1")
        VerifyCreditCardRq verifyCreditCardRq
    ) throws VerifyCreditCardFault1;

    @WebMethod(action = "paymentCreditCard")
    @WebResult(name = "PaymentCreditCardRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1", partName = "PaymentCreditCardRs")
    public PaymentCreditCardRs paymentCreditCard(
        @WebParam(partName = "PaymentCreditCardRq", name = "PaymentCreditCardRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/payment/v1")
        PaymentCreditCardRq paymentCreditCardRq
    ) throws PaymentCreditCardFault1;
}
