
package co.com.kallsonys.payment.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-01T18:20:43.265-05:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "exceptionGeneric", targetNamespace = "http://www.kallsonys.com.co/cim/common/exceptiongeneric")
public class PaymentCreditCardFault1 extends Exception {
    
    private co.com.kallsonys.payment.ws.ExceptionGeneric exceptionGeneric;

    public PaymentCreditCardFault1() {
        super();
    }
    
    public PaymentCreditCardFault1(String message) {
        super(message);
    }
    
    public PaymentCreditCardFault1(String message, Throwable cause) {
        super(message, cause);
    }

    public PaymentCreditCardFault1(String message, co.com.kallsonys.payment.ws.ExceptionGeneric exceptionGeneric) {
        super(message);
        this.exceptionGeneric = exceptionGeneric;
    }

    public PaymentCreditCardFault1(String message, co.com.kallsonys.payment.ws.ExceptionGeneric exceptionGeneric, Throwable cause) {
        super(message, cause);
        this.exceptionGeneric = exceptionGeneric;
    }

    public co.com.kallsonys.payment.ws.ExceptionGeneric getFaultInfo() {
        return this.exceptionGeneric;
    }
}
