package co.com.kallsonys.esb.brms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-11-04T19:40:55.597-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1", name = "BRMSPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BRMSPortType {

    @WebMethod(action = "defineShipmentCompany")
    @WebResult(name = "DefineShipmentCompanyRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1", partName = "DefineShipmentCompanyRs")
    public DefineShipmentCompanyRs defineShipmentCompany(
        @WebParam(partName = "DefineShipmentCompanyRq", name = "DefineShipmentCompanyRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1")
        DefineShipmentCompanyRq defineShipmentCompanyRq
    ) throws DefineShipmentCompanyFault1;

    @WebMethod(action = "validateAmountAccordingCustomerClass")
    @WebResult(name = "ValidateAmountAccordingCustomerClassRs", targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1", partName = "ValidateAmountAccordingCustomerClassRs")
    public ValidateAmountAccordingCustomerClassRs validateAmountAccordingCustomerClass(
        @WebParam(partName = "ValidateAmountAccordingCustomerClassRq", name = "ValidateAmountAccordingCustomerClassRq", targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1")
        ValidateAmountAccordingCustomerClassRq validateAmountAccordingCustomerClassRq
    ) throws ValidateAmountAccordingCustomerClassFault1;
}
