package co.com.kallsonys.esb.brms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-11-04T19:40:55.603-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "BRMSService", 
                  wsdlLocation = "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/04_BRMS/wsdl/1.2/brms.wsdl",
                  targetNamespace = "http://www.kallsonys.com.co/cim/message/brms/v1") 
public class BRMSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.kallsonys.com.co/cim/message/brms/v1", "BRMSService");
    public final static QName BRMSPort = new QName("http://www.kallsonys.com.co/cim/message/brms/v1", "BRMSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/04_BRMS/wsdl/1.2/brms.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BRMSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workspacePUJ/GitHub/kallsonys/esb/app/mule/Kallsonys/src/main/wsdl/01_ESB/Message/04_BRMS/wsdl/1.2/brms.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BRMSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BRMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BRMSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BRMSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BRMSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BRMSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BRMSPortType
     */
    @WebEndpoint(name = "BRMSPort")
    public BRMSPortType getBRMSPort() {
        return super.getPort(BRMSPort, BRMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BRMSPortType
     */
    @WebEndpoint(name = "BRMSPort")
    public BRMSPortType getBRMSPort(WebServiceFeature... features) {
        return super.getPort(BRMSPort, BRMSPortType.class, features);
    }

}
