
package co.com.kallsonys.esb.brms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-11-04T19:40:55.584-05:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "exceptionGeneric", targetNamespace = "http://www.kallsonys.com.co/cim/common/exceptiongeneric")
public class DefineShipmentCompanyFault1 extends Exception {
    
    private co.com.kallsonys.esb.brms.ExceptionGeneric exceptionGeneric;

    public DefineShipmentCompanyFault1() {
        super();
    }
    
    public DefineShipmentCompanyFault1(String message) {
        super(message);
    }
    
    public DefineShipmentCompanyFault1(String message, Throwable cause) {
        super(message, cause);
    }

    public DefineShipmentCompanyFault1(String message, co.com.kallsonys.esb.brms.ExceptionGeneric exceptionGeneric) {
        super(message);
        this.exceptionGeneric = exceptionGeneric;
    }

    public DefineShipmentCompanyFault1(String message, co.com.kallsonys.esb.brms.ExceptionGeneric exceptionGeneric, Throwable cause) {
        super(message, cause);
        this.exceptionGeneric = exceptionGeneric;
    }

    public co.com.kallsonys.esb.brms.ExceptionGeneric getFaultInfo() {
        return this.exceptionGeneric;
    }
}
